services:
  tueri_api:
    build:
      context: ..
      dockerfile: tueri_api/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - AUTH_TOKEN=example-auth-token
      - LOG_LEVEL=DEBUG
      - APP_WORKERS=1
      - SCAN_FAIL_FAST=true
      # - CACHE_MAX_SIZE=1000
      # - CACHE_TTL=3600
    restart: unless-stopped
    volumes:
      - ./config/scanners.yml:/home/user/app/config/scanners.yml
