name: Dev Publish

on:
  push:
    branches:
      - 'integration'

jobs:
  dev-publish:
    name: Dev Publish
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v2
      with:
        registry-type: public

    - name: Build and push Docker image
      run: |
        docker build -t public.ecr.aws/microhealthllc/tueri:dev .
        docker push public.ecr.aws/microhealthllc/tueri:dev